### ISSUE TITLE
ControllerResolver fails when parameter with default value is not provided

### ISSUE THREAD

**Issue by felixfbecker** [PHP-DI/Silex-Bridge#23]
A controller like this:
```php
$app->get('/hello/{world}', function (string $world = 'world') {
  
});
```
should work with this request:
```
GET /hello
```
but fails with
```
Controller requires that you provide a value for the "$world" argument.
```
This is because the `ResolverChain` used for resolving the controller parameters does not include a `DefaultValueResolver`:

https://github.com/PHP-DI/Silex-Bridge/blob/master/src/Application.php#L77

**Comment by mnapoli** [comment]
:+1: I don't remember if there's a reason for that, but my reasoning would be: if it doesn't break any test then it's safe to add the `DefaultValueResolver` ;)

**Comment by mnapoli** [comment]
Thank you for the PR, I've tagged [1.5.2](https://github.com/PHP-DI/Silex-Bridge/releases/tag/1.5.2)
